# === ESPHome ===
esphome:
  name: pet-feeder
  platform: ESP8266
  board: esp12e
  on_boot:
    priority: -100
    then:
      - light.turn_on: 
          id: status_led
          effect: "Asymmetrical Pulse"
logger:
  level: DEBUG
api:
  password: ""
ota:
  - platform: esphome
    password: ""
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Pet Feeder Fallback Hotspot"
    password: "yELlzkBPI0Mh"
captive_portal:


web_server:
  port: 80
  ota: true

# === Hardware ===
stepper:
  - platform: a4988
    id: feeder_motor
    step_pin: GPIO14
    dir_pin:  GPIO16
    sleep_pin: # Connected to EN pin
      number: GPIO12
      inverted: yes
    max_speed: 2300 steps/s
    # acceleration: 3500 steps/s^2
output:
  - platform: esp8266_pwm
    pin: GPIO13
    id: led_output
light:
  - platform: monochromatic
    output: led_output
    id: status_led
    name: "Status LED"
    effects:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
          min_brightness: 0%
          max_brightness: 100%
      - pulse:
          name: "Asymmetrical Pulse"
          transition_length:
            on_length: 1s
            off_length: 500ms
          update_interval: 1.5s
binary_sensor:
  - platform: gpio
    id: touch_button
    pin:
      number: GPIO05
      mode:
        input: true
        pullup: true
    on_double_click:
      then:
        - button.press: feed

# === Features and Logic ===
globals:
  - id: stepper_steps
    type: int
    initial_value: '200'
  - id: stepper_micro_steps
    type: int
    initial_value: '16'
  - id: stepper_gear_ratio
    type: float
    initial_value: '5.16'

number:
  - platform: template
    name: "Portions today"
    id: portions_today
    optimistic: true
    min_value: 0
    max_value: 7
    step: 1
    restore_value: true
    initial_value: 0
  - platform: template
    name: "Kibble loaded"
    id: kibble_stock
    optimistic: true
    min_value: 0
    max_value: 1000
    step: 10.6 # Portion weight in g
    restore_value: true
    initial_value: 0.0

text_sensor:
  - platform: template
    name: "Last fed"
    id: last_fed

# === Feed ===
button:
  - platform: template
    id: feed
    name: Feed
    icon: "mdi:food-drumstick"
    on_press:
      then:
      - light.turn_on: 
          id: status_led
          effect: "Fast Pulse"
      - stepper.report_position:
          id: feeder_motor
          position: 0
      - stepper.set_target:
          id: feeder_motor
          target: -500 # Ensure no kibble is stuck
      - delay: 2000ms
      - stepper.set_target:
          id: feeder_motor
          target: !lambda return id(stepper_steps) * id(stepper_micro_steps) * id(stepper_gear_ratio) / 4 / 2; # Quarter turn, divided in 2 again to feed smaller portions
      - number.increment: portions_today
      - number.decrement: kibble_stock
      - text_sensor.template.publish:
          id: last_fed
          state: !lambda return id(sntp_time).now().strftime("%Y-%m-%d %H:%M").c_str();
      - delay: 3000ms
      - light.turn_on: 
          id: status_led
          effect: "Asymmetrical Pulse"

# === Schedule ===
time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Brussels
    on_time:
      # Midnight
      - seconds: 0
        minutes: 0
        hours: 0
        then:
          - number.set:
              id: portions_today
              value: 0
          - logger.log: "Midnight, reset daily feeding counter"

      # Weekdays
      - seconds: 0
        hours: 7
        minutes: 15
        days_of_week: MON-FRI
        then:
          - button.press: feed
          - delay: 6000ms
          - button.press: feed
      - seconds: 0
        hours: 11
        minutes: 30
        days_of_week: MON-FRI
        then:
          - button.press: feed
      - seconds: 0
        hours: 15
        minutes: 30
        days_of_week: MON-FRI
        then:
          - button.press: feed
      - seconds: 0
        hours: 19
        minutes: 00
        days_of_week: MON-FRI
        then:
          - button.press: feed
      - seconds: 0
        hours: 23
        minutes: 00
        days_of_week: MON-FRI
        then:
          - button.press: feed
          - delay: 6000ms
          - button.press: feed

      # Weekends
      - seconds: 0
        hours: 8
        minutes: 30
        days_of_week: SAT,SUN
        then:
          - button.press: feed
          - delay: 6000ms
          - button.press: feed
      - seconds: 0
        hours: 13
        minutes: 00
        days_of_week: SAT,SUN
        then:
          - button.press: feed
      - seconds: 0
        hours: 16
        minutes: 30
        days_of_week: SAT,SUN
        then:
          - button.press: feed
      - seconds: 0
        hours: 19
        minutes: 30
        days_of_week: SAT,SUN
        then:
          - button.press: feed
      - seconds: 0
        hours: 23
        minutes: 30
        days_of_week: SAT,SUN
        then:
          - button.press: feed
          - delay: 6000ms
          - button.press: feed